language: java
jdk:
  - openjdk8

services:
  - redis

env:
  - ORG_GRADLE_PROJECT_sonatypeUsername=xxx
  - ORG_GRADLE_PROJECT_sonatypePassword=xxx
  - USER_NAME=rqueue

cache:
  directories:
    - $HOME/.gradle

jobs:
  include:
    - stage: spring-boot-2.1
      env:
        - SPRING_BOOT_VERSION=2.1.0.RELEASE
        - SPRING_VERSION=5.1.2.RELEASE
        - SPRING_DATA_VERSION=2.1.2.RELEASE
        - MICROMETER_VERSION=1.1.0
      script:
        - ./gradlew check
        - ./gradlew codeCoverageReport
    - stage: spring-boot-2.2
      env:
        - SPRING_BOOT_VERSION=2.2.0.RELEASE
        - SPRING_VERSION=5.2.0.RELEASE
        - SPRING_DATA_VERSION=2.2.0.RELEASE
        - MICROMETER_VERSION=1.3.2
      script:
        - ./gradlew check
        - ./gradlew codeCoverageReport

stages:
  - spring-boot-2.1
  - spring-boot-2.2

notifications:
  email:
    - sonunitw12@gmail.com

after_success:
  - ./gradlew coveralls
